### ISSUE TITLE
Link to invoke specific module or function do not work

### ISSUE THREAD

**Issue by rlouapre** [robwhitby/xray#32]
I can reproduce the issue when the directory is not ```test```.
I will provide a fix in ```html.xsl``` but I am not sure if it the best way to fix it.
I try to provide from xquery code a sequence element
```
<module>
  <absolute-path>c:/my-app/foo/test/test.xqy</absolute-path>
  <relative-path>test/test.xqy</relative-path>
</module>
```
where c:/my-app/foo is my test directory.  
But there is a clause https://github.com/robwhitby/xray/blob/master/src/modules.xqy#L23 to prevent relative path.

**Comment by robwhitby** [comment]
This should be fixed now

**Comment by rlouapre** [comment]
+1
