### ISSUE TITLE
path separators

### ISSUE THREAD

**Issue by wakingrufus** [robwhitby/xray#43]
in our code, we import modules using only forward slashes "/". We run marklogic on both windows and linux. on the windows machines, marklogic can inerpret our import paths just fine. However, in xray, when tests execute, we get "inconsistent module import" errors because xray has "\" in the path, which i assume is from scanning the directory for test modules within a windows environment.  I was able to work around this by changing https://github.com/robwhitby/xray/blob/master/src/modules-filesystem.xqy#L12 to replace \ with / and never the other way.  Is there a better way to solve this problem?  Is this something that can be configured for in xray, or is it a bug?

**Comment by rlouapre** [comment]
Seems to be related to #32

**Comment by robwhitby** [comment]
hi, sorry for the delay, had to setup a windows vm to test this on. I didn't realise forward slashes would work on windows, that simplifies things. Please try pulling the latest from master and re-open the issue if there's still a problem.

**Comment by wakingrufus** [comment]
It works! Thanks so much!
