### ISSUE TITLE
Q: will you be doing anything with SJS? 

### ISSUE THREAD

**Issue by dmcassel** [robwhitby/xray#45]
A full mix would allow testing XQuery libraries with XQuery code, Server-side JavaScript libraries with XQuery code, XQuery with SJS, and SJS with SJS. I'm curious whether you plan to expand beyond XQuery/XQuery.

**Comment by robwhitby** [comment]
I've thought about it - it does seem like a logical addition, but haven't actually done anything yet. The main stumbling block is I'm still working with ML7 so haven't really delved into SJS. Maybe I'll get inspiration from the conference :)

**Comment by dmcassel** [comment]
I'm discussing XRay in my Continuous Integration talk at MLW. As it stands, I mention that it covers XQuery/XQuery. Please let me know if you'd like me to add a roadmap note. See you there!

**Comment by robwhitby** [comment]
There's nothing concrete for a roadmap, it will be interesting to hear what people would like.
