### ISSUE TITLE
json format performance problems

### ISSUE THREAD

**Issue by wakingrufus** [robwhitby/xray#46]
when running a small suite of tests, we have not had a problem running xray with format=json, but with one of our larger test suites, we have seen the performance of the json conversion suffer.
for example html takes ~20 sec, json fails at our timeout limit of 10 min.

**Comment by wakingrufus** [comment]
Apparently json converts all objects you are asserting on, where as the html doesn't do this, and that is what contributed to this difference.

**Comment by robwhitby** [comment]
Hi, I can't seem to reproduce this, for me json/xml/html/text are all pretty much equal. What version of ML are you on? Or maybe it happens under specific conditions - failure output or something?

**Comment by xquery** [comment]
what version of ML are you using ?
