### ISSUE TITLE
Want to return $message in assertion as type item()?

### ISSUE THREAD

**Issue by xquery-guy** [robwhitby/xray#53]
Want to add this function to assertions.xqy:

declare function assert:equal(
  $actual as item()*,
  $expected as item()*,
  $message as item()?,
  $item-type as xs:boolean
) as element(xray:assert)
{
  if ($item-type) then
    let $status := deep-equal($actual, $expected)
    return xray:assert-response("equal", $status, $actual, $expected, $message)
  else
    assert:equal($actual, $expected, $message)
};

The purpose is that I want to be able to return xml in the $message.
Using xdmp:quote so that $message is of type string and doing string play
only gets you as far as having the < and > come out as & lt; and & gt;

**Comment by robwhitby** [comment]
Hi, I don't understand why it would be useful to have xml in the message. It's purpose is to add some explanatory text to help debugging a failure. How are you intending to use it? Maybe adding a new output format would work better
