### ISSUE TITLE
Testing write/update operations

### ISSUE THREAD

**Issue by timbarclay** [robwhitby/xray#59]
Is there a recommended way to test a function that writes or updates a document in the database?

If I have a test like the following:

    declare %test:case function write-test {
        let $id := "doc-1"
        let $doc := <aDocument id="{$id}">content</aDocument>
        let $_ := write-a-document($id, $doc)
        let $result := get-a-document($id)
        return assert:equal($doc, $result)
    }

at the point the assertion runs, the transaction hasn't been committed so it's not able to get the document.

Is there a way to handle this use case in XRay?

**Comment by robwhitby** [comment]
hey, you can use the setup and teardown functions like this - https://github.com/robwhitby/xray/blob/master/test/setup-teardown.xqy
